spring.datasource.url=jdbc:postgresql://localhost:5432/accounting-project
spring.datasource.username=postgres
spring.datasource.password=151690
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=8000

STRIPE_PUBLIC_KEY = pk_test_51RVIdvFovEODgt4N1dn3rtp9WmCbZo4v7OxU2OQTiGyQww3NgcFM4bx7LmEDzmecVCmxAm7ZXQHJ31D9P5a2fkH700XQf3m9xh
STRIPE_API_SECRET = sk_test_51RVIdvFovEODgt4Ny9MV2FbgONlfnK391GmigUdrKKYcJ24iaeOJO3ITFASK7V52cUjiWPzPcnhXohhAp7zajErC007uMoMDDj
