property.filename =./logs

appenders = console, rolling

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

loggers = file
logger.file.name = com.cydeo.aspect
logger.file.level = INFO
logger.file.appenderRefs = file
logger.file.appenderRef.file.ref = LOGFILE

appender.rolling.type = RollingFile
appender.rolling.name = fileLogger
appender.rolling.fileName= rolling_app.log
appender.rolling.filePattern= rolling_app%d{yyyy-MM-dd HH:mm}.log
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%t] [%l] - %msg%n
appender.rolling.policies.type = Policies

# RollingFileAppender rotation policy
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 5Kb
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 2
appender.rolling.policies.time.modulate = true
appender.rolling.strategy.type = DefaultRolloverStrategy
rootLogger.appenderRef.rolling.ref = fileLogger

rootLogger.level = INFO
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT